<?php

namespace ContainerQGSK53d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IKoxby9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iKoxby9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iKoxby9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'team' => ['privates', '.errored..service_locator.iKoxby9.App\\Entity\\Team', NULL, 'Cannot autowire service ".service_locator.iKoxby9": it needs an instance of "App\\Entity\\Team" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'team' => 'App\\Entity\\Team',
            'entityManager' => '?',
        ]);
    }
}
