nelmio_api_doc:
  documentation:
    info:
      title: "API Dokumentace"
      description: "API k bakálářské práci SportMatter<br> @Šimon Hrdý 2025"
      version: "1.0.0"
    components:
      securitySchemes:
        BearerAuth:
          type: http
          scheme: bearer
    security:
      - BearerAuth: []
    use_validation_groups: true
    paths:
      /api/login_check:
        post:
          tags:
            - Login
          summary: "Přihlášení uživatele"
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
                      format: password
          responses:
            200:
              description: "Úspěšné přihlášení"
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      token:
                        type: string
            401:
              description: "Neplatné přihlašovací údaje"

