security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/verify-token, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/, roles: IS_AUTHENTICATED_FULLY,  methods: [ POST, PUT, DELETE ] }
        - { path: ^/api/players/, roles: IS_AUTHENTICATED_FULLY, methods: [ POST, PUT, DELETE ] }
        - { path: ^/api/teams/, roles: IS_AUTHENTICATED_FULLY, methods: [ POST, PUT, DELETE ] }
        - { path: ^/api/countries/, roles: IS_AUTHENTICATED_FULLY, methods: [ POST, PUT, DELETE ] }
        - { path: ^/api/stadiums/, roles: IS_AUTHENTICATED_FULLY, methods: [ POST, PUT, DELETE ] }
        - { path: ^/api/sports/, roles: IS_AUTHENTICATED_FULLY, methods: [ POST, PUT, DELETE ] }
        - { path: ^/api/seasons/, roles: IS_AUTHENTICATED_FULLY, methods: [ POST, PUT, DELETE ] }
        - { path: ^/api/referees/, roles: IS_AUTHENTICATED_FULLY, methods: [ POST, PUT, DELETE ] }
        - { path: ^/api/game/, roles: IS_AUTHENTICATED_FULLY, methods: [ POST, PUT, DELETE ] }
        - { path: ^/api/league/, roles: IS_AUTHENTICATED_FULLY, methods: [ POST, PUT, DELETE ] }
        - { path: ^/api/player-history, roles: IS_AUTHENTICATED_FULLY, methods: [ POST, PUT, DELETE ] }
        - { path: ^/api/player-stats, roles: IS_AUTHENTICATED_FULLY, methods: [ POST, PUT, DELETE ] }
