<?php

namespace ContainerUf7zqgB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCountryControllergetCountryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ga2YqgV.App\Controller\CountryController::getCountry()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ga2YqgV.App\\Controller\\CountryController::getCountry()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'country' => ['privates', '.errored..service_locator.Ga2YqgV.App\\Entity\\Country', NULL, 'Cannot autowire service ".service_locator.Ga2YqgV": it needs an instance of "App\\Entity\\Country" but this type has been excluded in "config/services.yaml".'],
        ], [
            'country' => 'App\\Entity\\Country',
        ]))->withContext('App\\Controller\\CountryController::getCountry()', $container);
    }
}
