<?php

namespace ContainerUf7zqgB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeagueControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZKf94C1.App\Controller\LeagueController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZKf94C1.App\\Controller\\LeagueController::delete()'] = ($container->privates['.service_locator.ZKf94C1'] ?? $container->load('get_ServiceLocator_ZKf94C1Service'))->withContext('App\\Controller\\LeagueController::delete()', $container);
    }
}
