<?php

namespace ContainerUf7zqgB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSportControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SportController' shared autowired service.
     *
     * @return \App\Controller\SportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SportController.php';

        $container->services['App\\Controller\\SportController'] = $instance = new \App\Controller\SportController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\SportController', $container));

        return $instance;
    }
}
