<?php

namespace ContainerUDbxpyP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WQVGjS2.App\Entity\Game' shared service.
     *
     * @return \App\Entity\Game
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.WQVGjS2": it needs an instance of "App\\Entity\\Game" but this type has been excluded in "config/services.yaml".');
    }
}
