<?php

namespace ContainerUDbxpyP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerHistoryControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.67Lrj0G.App\Controller\PlayerHistoryController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.67Lrj0G.App\\Controller\\PlayerHistoryController::delete()'] = ($container->privates['.service_locator.67Lrj0G'] ?? $container->load('get_ServiceLocator_67Lrj0GService'))->withContext('App\\Controller\\PlayerHistoryController::delete()', $container);
    }
}
