<?php

namespace ContainerUDbxpyP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStadiumControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xPCGtRu.App\Controller\StadiumController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xPCGtRu.App\\Controller\\StadiumController::delete()'] = ($container->privates['.service_locator.xPCGtRu'] ?? $container->load('get_ServiceLocator_XPCGtRuService'))->withContext('App\\Controller\\StadiumController::delete()', $container);
    }
}
