<?php

namespace Container3XG5qrk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameControllergetGameService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WQVGjS2.App\Controller\GameController::getGame()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WQVGjS2.App\\Controller\\GameController::getGame()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'game' => ['privates', '.errored..service_locator.WQVGjS2.App\\Entity\\Game', NULL, 'Cannot autowire service ".service_locator.WQVGjS2": it needs an instance of "App\\Entity\\Game" but this type has been excluded in "config/services.yaml".'],
        ], [
            'game' => 'App\\Entity\\Game',
        ]))->withContext('App\\Controller\\GameController::getGame()', $container);
    }
}
