<?php

namespace Container3XG5qrk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerHistory2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GIlnGoK.App\Entity\PlayerHistory' shared service.
     *
     * @return \App\Entity\PlayerHistory
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.GIlnGoK": it needs an instance of "App\\Entity\\PlayerHistory" but this type has been excluded in "config/services.yaml".');
    }
}
