<?php

namespace Container3XG5qrk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MSzna8D.App\Entity\Player' shared service.
     *
     * @return \App\Entity\Player
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MSzna8D": it needs an instance of "App\\Entity\\Player" but this type has been excluded in "config/services.yaml".');
    }
}
