<?php

namespace Container3XG5qrk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeasonControllergetSeasonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JTDwdNm.App\Controller\SeasonController::getSeason()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JTDwdNm.App\\Controller\\SeasonController::getSeason()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'season' => ['privates', '.errored..service_locator.JTDwdNm.App\\Entity\\Season', NULL, 'Cannot autowire service ".service_locator.JTDwdNm": it needs an instance of "App\\Entity\\Season" but this type has been excluded in "config/services.yaml".'],
        ], [
            'season' => 'App\\Entity\\Season',
        ]))->withContext('App\\Controller\\SeasonController::getSeason()', $container);
    }
}
