<?php

namespace Container3XG5qrk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iKoxby9.App\Controller\TeamController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iKoxby9.App\\Controller\\TeamController::delete()'] = ($container->privates['.service_locator.iKoxby9'] ?? $container->load('get_ServiceLocator_IKoxby9Service'))->withContext('App\\Controller\\TeamController::delete()', $container);
    }
}
