<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Team extends \App\Entity\Team implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'coach' => [parent::class, 'coach', null],
        "\0".parent::class."\0".'games_away' => [parent::class, 'games_away', null],
        "\0".parent::class."\0".'games_home' => [parent::class, 'games_home', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'image_src' => [parent::class, 'image_src', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'playerHistories' => [parent::class, 'playerHistories', null],
        "\0".parent::class."\0".'players' => [parent::class, 'players', null],
        "\0".parent::class."\0".'seasonHasTeams' => [parent::class, 'seasonHasTeams', null],
        "\0".parent::class."\0".'short_name' => [parent::class, 'short_name', null],
        "\0".parent::class."\0".'stadium_id' => [parent::class, 'stadium_id', null],
        "\0".parent::class."\0".'surname' => [parent::class, 'surname', null],
        "\0".parent::class."\0".'userHasFavoriteTeams' => [parent::class, 'userHasFavoriteTeams', null],
        'coach' => [parent::class, 'coach', null],
        'games_away' => [parent::class, 'games_away', null],
        'games_home' => [parent::class, 'games_home', null],
        'id' => [parent::class, 'id', null],
        'image_src' => [parent::class, 'image_src', null],
        'name' => [parent::class, 'name', null],
        'playerHistories' => [parent::class, 'playerHistories', null],
        'players' => [parent::class, 'players', null],
        'seasonHasTeams' => [parent::class, 'seasonHasTeams', null],
        'short_name' => [parent::class, 'short_name', null],
        'stadium_id' => [parent::class, 'stadium_id', null],
        'surname' => [parent::class, 'surname', null],
        'userHasFavoriteTeams' => [parent::class, 'userHasFavoriteTeams', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
