<?php

namespace ContainerSjnKY3Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XPCGtRuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xPCGtRu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xPCGtRu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'stadium' => ['privates', '.errored..service_locator.xPCGtRu.App\\Entity\\Stadium', NULL, 'Cannot autowire service ".service_locator.xPCGtRu": it needs an instance of "App\\Entity\\Stadium" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'stadium' => 'App\\Entity\\Stadium',
            'entityManager' => '?',
        ]);
    }
}
