<?php

namespace ContainerSjnKY3Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameControllergetByDateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pnT1m7p.App\Controller\GameController::getByDate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pnT1m7p.App\\Controller\\GameController::getByDate()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'gameRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
        ], [
            'gameRepository' => 'App\\Repository\\GameRepository',
        ]))->withContext('App\\Controller\\GameController::getByDate()', $container);
    }
}
