<?php

namespace ContainerSjnKY3Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeague2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.orDyv_R.App\Entity\League' shared service.
     *
     * @return \App\Entity\League
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.orDyv_R": it needs an instance of "App\\Entity\\League" but this type has been excluded in "config/services.yaml".');
    }
}
