<?php

namespace ContainerSjnKY3Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Describers_ConfigService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'nelmio_api_doc.describers.config' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/src/Describer/DescriberInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/src/Describer/ExternalDocDescriber.php';

        return $container->privates['nelmio_api_doc.describers.config'] = new \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber(['info' => ['title' => 'API Dokumentace', 'description' => 'API k bakálářské práci SportMatter<br> @Šimon Hrdý 2025', 'version' => '1.0.0'], 'components' => ['securitySchemes' => ['BearerAuth' => ['type' => 'http', 'scheme' => 'bearer']]], 'security' => [['BearerAuth' => []]], 'use_validation_groups' => true, 'paths' => ['/api/login_check' => ['post' => ['tags' => ['Login'], 'summary' => 'Přihlášení uživatele', 'requestBody' => ['required' => true, 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['username' => ['type' => 'string'], 'password' => ['type' => 'string', 'format' => 'password']]]]]], 'responses' => [200 => ['description' => 'Úspěšné přihlášení', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['token' => ['type' => 'string']]]]]], 401 => ['description' => 'Neplatné přihlašovací údaje']]]]]]);
    }
}
