<?php

namespace ContainerOpwSwpE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameDateControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GameDateController' shared autowired service.
     *
     * @return \App\Controller\GameDateController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GameDateController.php';

        $container->services['App\\Controller\\GameDateController'] = $instance = new \App\Controller\GameDateController(($container->privates['App\\Repository\\GameRepository'] ?? $container->load('getGameRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\GameDateController', $container));

        return $instance;
    }
}
