<?php

namespace ContainerEoZJtiv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerStatsControllergetPlayerStatsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3H2dEZZ.App\Controller\PlayerStatsController::getPlayerStats()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3H2dEZZ.App\\Controller\\PlayerStatsController::getPlayerStats()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'playerStats' => ['privates', '.errored..service_locator.3H2dEZZ.App\\Entity\\PlayerStats', NULL, 'Cannot autowire service ".service_locator.3H2dEZZ": it needs an instance of "App\\Entity\\PlayerStats" but this type has been excluded in "config/services.yaml".'],
        ], [
            'playerStats' => 'App\\Entity\\PlayerStats',
        ]))->withContext('App\\Controller\\PlayerStatsController::getPlayerStats()', $container);
    }
}
