<?php

namespace ContainerEoZJtiv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerControllergetPlayerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vSzgaud.App\Controller\PlayerController::getPlayer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vSzgaud.App\\Controller\\PlayerController::getPlayer()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'player' => ['privates', '.errored..service_locator.vSzgaud.App\\Entity\\Player', NULL, 'Cannot autowire service ".service_locator.vSzgaud": it needs an instance of "App\\Entity\\Player" but this type has been excluded in "config/services.yaml".'],
        ], [
            'player' => 'App\\Entity\\Player',
        ]))->withContext('App\\Controller\\PlayerController::getPlayer()', $container);
    }
}
