<?php

namespace ContainerEoZJtiv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefereeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RefereeController' shared autowired service.
     *
     * @return \App\Controller\RefereeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/RefereeController.php';

        $container->services['App\\Controller\\RefereeController'] = $instance = new \App\Controller\RefereeController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\RefereeController', $container));

        return $instance;
    }
}
