<?php

namespace ContainerEoZJtiv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefereeControllergetRefereeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hUIigMv.App\Controller\RefereeController::getReferee()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hUIigMv.App\\Controller\\RefereeController::getReferee()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'referee' => ['privates', '.errored..service_locator.hUIigMv.App\\Entity\\Referee', NULL, 'Cannot autowire service ".service_locator.hUIigMv": it needs an instance of "App\\Entity\\Referee" but this type has been excluded in "config/services.yaml".'],
        ], [
            'referee' => 'App\\Entity\\Referee',
        ]))->withContext('App\\Controller\\RefereeController::getReferee()', $container);
    }
}
