<?php

namespace ContainerEoZJtiv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSportControllergetSportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UCBsVir.App\Controller\SportController::getSport()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UCBsVir.App\\Controller\\SportController::getSport()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sport' => ['privates', '.errored..service_locator.UCBsVir.App\\Entity\\Sport', NULL, 'Cannot autowire service ".service_locator.UCBsVir": it needs an instance of "App\\Entity\\Sport" but this type has been excluded in "config/services.yaml".'],
        ], [
            'sport' => 'App\\Entity\\Sport',
        ]))->withContext('App\\Controller\\SportController::getSport()', $container);
    }
}
