<?php

namespace ContainerEoZJtiv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStadiumService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Wd8atRm.App\Entity\Stadium' shared service.
     *
     * @return \App\Entity\Stadium
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Wd8atRm": it needs an instance of "App\\Entity\\Stadium" but this type has been excluded in "config/services.yaml".');
    }
}
