<?php

namespace ContainerYhTbyz3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllergetUserDataService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3Z_NNSR.App\Controller\UserController::getUserData()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3Z_NNSR.App\\Controller\\UserController::getUserData()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'JWTTokenManager' => ['services', 'lexik_jwt_authentication.jwt_manager', 'getLexikJwtAuthentication_JwtManagerService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'JWTTokenManager' => '?',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\UserController::getUserData()', $container);
    }
}
