<?php

namespace Container2zYoUcp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MSzna8DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MSzna8D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MSzna8D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'player' => ['privates', '.errored..service_locator.MSzna8D.App\\Entity\\Player', NULL, 'Cannot autowire service ".service_locator.MSzna8D": it needs an instance of "App\\Entity\\Player" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'player' => 'App\\Entity\\Player',
            'entityManager' => '?',
        ]);
    }
}
