<?php

namespace Container2zYoUcp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerHistoryControllergetPlayerHistoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GIlnGoK.App\Controller\PlayerHistoryController::getPlayerHistory()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GIlnGoK.App\\Controller\\PlayerHistoryController::getPlayerHistory()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'playerHistory' => ['privates', '.errored..service_locator.GIlnGoK.App\\Entity\\PlayerHistory', NULL, 'Cannot autowire service ".service_locator.GIlnGoK": it needs an instance of "App\\Entity\\PlayerHistory" but this type has been excluded in "config/services.yaml".'],
        ], [
            'playerHistory' => 'App\\Entity\\PlayerHistory',
        ]))->withContext('App\\Controller\\PlayerHistoryController::getPlayerHistory()', $container);
    }
}
