<?php

namespace Container2zYoUcp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeasonControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lnv_epI.App\Controller\SeasonController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lnv_epI.App\\Controller\\SeasonController::list()'] = ($container->privates['.service_locator.Lnv_epI'] ?? $container->load('get_ServiceLocator_LnvEpIService'))->withContext('App\\Controller\\SeasonController::list()', $container);
    }
}
