<?php

namespace ContainerS2cor9s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6gZypo7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6gZypo7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6gZypo7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'playerStats' => ['privates', '.errored..service_locator.6gZypo7.App\\Entity\\PlayerStats', NULL, 'Cannot autowire service ".service_locator.6gZypo7": it needs an instance of "App\\Entity\\PlayerStats" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'playerStats' => 'App\\Entity\\PlayerStats',
            'entityManager' => '?',
        ]);
    }
}
