<?php

namespace ContainerS2cor9s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_GX8LbYeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.GX8LbYe' shared service.
     *
     * @return \App\Controller\MailerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\UserController::forgotPassword()": the $mailer argument is type-hinted with the non-existent class or interface: "App\\Controller\\MailerInterface". Did you forget to add a use statement?');
    }
}
