<?php

namespace ContainerS2cor9s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCountry2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ga2YqgV.App\Entity\Country' shared service.
     *
     * @return \App\Entity\Country
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Ga2YqgV": it needs an instance of "App\\Entity\\Country" but this type has been excluded in "config/services.yaml".');
    }
}
