<?php

namespace ContainerS2cor9s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerStatsControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6gZypo7.App\Controller\PlayerStatsController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6gZypo7.App\\Controller\\PlayerStatsController::update()'] = ($container->privates['.service_locator.6gZypo7'] ?? $container->load('get_ServiceLocator_6gZypo7Service'))->withContext('App\\Controller\\PlayerStatsController::update()', $container);
    }
}
