<?php

namespace ContainerS2cor9s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerStatsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3H2dEZZ.App\Entity\PlayerStats' shared service.
     *
     * @return \App\Entity\PlayerStats
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3H2dEZZ": it needs an instance of "App\\Entity\\PlayerStats" but this type has been excluded in "config/services.yaml".');
    }
}
