<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHmKdxZI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHmKdxZI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHmKdxZI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHmKdxZI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHmKdxZI\App_KernelDevDebugContainer([
    'container.build_hash' => 'HmKdxZI',
    'container.build_id' => 'a0dff575',
    'container.build_time' => 1740149838,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHmKdxZI');
