<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSjnKY3Z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSjnKY3Z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSjnKY3Z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSjnKY3Z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSjnKY3Z\App_KernelDevDebugContainer([
    'container.build_hash' => 'SjnKY3Z',
    'container.build_id' => '15f88672',
    'container.build_time' => 1740091263,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSjnKY3Z');
