<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOpwSwpE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOpwSwpE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOpwSwpE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOpwSwpE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOpwSwpE\App_KernelDevDebugContainer([
    'container.build_hash' => 'OpwSwpE',
    'container.build_id' => 'da23a9ba',
    'container.build_time' => 1739824557,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOpwSwpE');
