<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'player_app_player_list' => [[], ['_controller' => 'App\\Controller\\PlayerController::list'], [], [['text', '/api/players']], [], [], []],
    'player_app_player_getone' => [['id'], ['_controller' => 'App\\Controller\\PlayerController::getOne'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/players']], [], [], []],
    'player_app_player_create' => [[], ['_controller' => 'App\\Controller\\PlayerController::create'], [], [['text', '/api/players']], [], [], []],
    'player_app_player_update' => [['id'], ['_controller' => 'App\\Controller\\PlayerController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/players']], [], [], []],
    'player_app_player_delete' => [['id'], ['_controller' => 'App\\Controller\\PlayerController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/players']], [], [], []],
    'user_app_user_list' => [[], ['_controller' => 'App\\Controller\\UserController::list'], [], [['text', '/api/users']], [], [], []],
    'user_app_user_getme' => [[], ['_controller' => 'App\\Controller\\UserController::getMe'], [], [['text', '/api/users/me']], [], [], []],
    'user_app_user_create' => [[], ['_controller' => 'App\\Controller\\UserController::create'], [], [['text', '/api/users']], [], [], []],
    'user_app_user_update' => [['id'], ['_controller' => 'App\\Controller\\UserController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'user_app_user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'user_app_user_changepassword' => [['id'], ['_controller' => 'App\\Controller\\UserController::changePassword'], [], [['text', '/change-password'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'user_app_user_forgotpassword' => [[], ['_controller' => 'App\\Controller\\UserController::forgotPassword'], [], [['text', '/api/users/forgot-password']], [], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/docs']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], [], []],
    'App\Controller\PlayerController::list' => [[], ['_controller' => 'App\\Controller\\PlayerController::list'], [], [['text', '/api/players']], [], [], []],
    'App\Controller\PlayerController::getOne' => [['id'], ['_controller' => 'App\\Controller\\PlayerController::getOne'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/players']], [], [], []],
    'App\Controller\PlayerController::create' => [[], ['_controller' => 'App\\Controller\\PlayerController::create'], [], [['text', '/api/players']], [], [], []],
    'App\Controller\PlayerController::update' => [['id'], ['_controller' => 'App\\Controller\\PlayerController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/players']], [], [], []],
    'App\Controller\PlayerController::delete' => [['id'], ['_controller' => 'App\\Controller\\PlayerController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/players']], [], [], []],
    'App\Controller\UserController::list' => [[], ['_controller' => 'App\\Controller\\UserController::list'], [], [['text', '/api/users']], [], [], []],
    'App\Controller\UserController::getMe' => [[], ['_controller' => 'App\\Controller\\UserController::getMe'], [], [['text', '/api/users/me']], [], [], []],
    'App\Controller\UserController::create' => [[], ['_controller' => 'App\\Controller\\UserController::create'], [], [['text', '/api/users']], [], [], []],
    'App\Controller\UserController::update' => [['id'], ['_controller' => 'App\\Controller\\UserController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'App\Controller\UserController::delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'App\Controller\UserController::changePassword' => [['id'], ['_controller' => 'App\\Controller\\UserController::changePassword'], [], [['text', '/change-password'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'App\Controller\UserController::forgotPassword' => [[], ['_controller' => 'App\\Controller\\UserController::forgotPassword'], [], [['text', '/api/users/forgot-password']], [], [], []],
];
