<?php

namespace ContainerHmKdxZI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeagueControllergetLeagueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PQMDegY.App\Controller\LeagueController::getLeague()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PQMDegY.App\\Controller\\LeagueController::getLeague()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'league' => ['privates', '.errored..service_locator.PQMDegY.App\\Entity\\League', NULL, 'Cannot autowire service ".service_locator.PQMDegY": it needs an instance of "App\\Entity\\League" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'league' => 'App\\Entity\\League',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\LeagueController::getLeague()', $container);
    }
}
