<?php

namespace ContainerHmKdxZI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReferee2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.l6oBZ.1.App\Entity\Referee' shared service.
     *
     * @return \App\Entity\Referee
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.l6oBZ.1": it needs an instance of "App\\Entity\\Referee" but this type has been excluded in "config/services.yaml".');
    }
}
