<?php

namespace ContainerHmKdxZI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeason2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VeIdmon.App\Entity\Season' shared service.
     *
     * @return \App\Entity\Season
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VeIdmon": it needs an instance of "App\\Entity\\Season" but this type has been excluded in "config/services.yaml".');
    }
}
