<?php

namespace ContainerHmKdxZI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamControllergetTeamService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ob08xeA.App\Controller\TeamController::getTeam()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ob08xeA.App\\Controller\\TeamController::getTeam()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'team' => ['privates', '.errored..service_locator.Ob08xeA.App\\Entity\\Team', NULL, 'Cannot autowire service ".service_locator.Ob08xeA": it needs an instance of "App\\Entity\\Team" but this type has been excluded in "config/services.yaml".'],
        ], [
            'team' => 'App\\Entity\\Team',
        ]))->withContext('App\\Controller\\TeamController::getTeam()', $container);
    }
}
